# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/Faculta/AN2/Sem 2/AC/ProiectMIPSfinal/ProiectMIPSfinal.cache/wt} [current_project]
set_property parent.project_path {D:/Faculta/AN2/Sem 2/AC/ProiectMIPSfinal/ProiectMIPSfinal.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/Faculta/AN2/Sem 2/AC/ProiectMIPSfinal/ProiectMIPSfinal.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {D:/Faculta/AN2/Sem 2/AC/ProiectMIPSfinal/ProiectMIPSfinal.srcs/sources_1/new/RegisterFile.vhd}
  {D:/Faculta/AN2/Sem 2/AC/ProiectMIPSfinal/ProiectMIPSfinal.srcs/sources_1/new/MEM.vhd}
  {D:/Faculta/AN2/Sem 2/AC/ProiectMIPSfinal/ProiectMIPSfinal.srcs/sources_1/new/InstructionFetch.vhd}
  {D:/Faculta/AN2/Sem 2/AC/ProiectMIPSfinal/ProiectMIPSfinal.srcs/sources_1/new/InstructionDecode.vhd}
  {D:/Faculta/AN2/Sem 2/AC/ProiectMIPSfinal/ProiectMIPSfinal.srcs/sources_1/new/ExecutionUnit.vhd}
  {D:/Faculta/AN2/Sem 2/AC/ProiectMIPSfinal/ProiectMIPSfinal.srcs/sources_1/new/SSD.vhd}
  {D:/Faculta/AN2/Sem 2/AC/ProiectMIPSfinal/ProiectMIPSfinal.srcs/sources_1/new/MPG.vhd}
  {D:/Faculta/AN2/Sem 2/AC/ProiectMIPSfinal/ProiectMIPSfinal.srcs/sources_1/new/MainControl.vhd}
  {D:/Faculta/AN2/Sem 2/AC/ProiectMIPSfinal/ProiectMIPSfinal.srcs/sources_1/new/test_env.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Faculta/AN2/Sem 2/AC/Basys3_test_env.xdc}}
set_property used_in_implementation false [get_files {{D:/Faculta/AN2/Sem 2/AC/Basys3_test_env.xdc}}]


synth_design -top test_env -part xc7a35tcpg236-1


write_checkpoint -force -noxdef test_env.dcp

catch { report_utilization -file test_env_utilization_synth.rpt -pb test_env_utilization_synth.pb }
